server:
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/thunderpets}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    show-sql: true
    format-sql: true
  social:
    google:
      appId: 701153196730-3m3mcg1lh3rajqakb5gno6q6vksgbno9.apps.googleusercontent.com
      appSecret: o_XqNaE6JlMFkM9Wa5cAnQrI
      redirectUri: http://localhost:8080/oauth/google/login
security:
  oauth2:
    client:
      client-id: ${OAUTH_CLIENT:client-id}
      client-secret: ${OAUTH_SECRET:secret-id}
flyway:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/thunderpets}
  user: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:postgres}
  baseline-on-migrate: true
  enabled: true
hibernate:
  jdbc:
    use_streams_for_binary: false