server:
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/thunderpets}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    show-sql: true
    format-sql: true
  social:
    google:
      appId: ${GOOGLE_CLIENT_ID}
      appSecret: ${GOOGLE_CLIENT_SECRET}
      redirectUri: ${GOOGLE_REDIRECT_URI:http://localhost:8081/oauth/google/login}
security:
  oauth2:
    client:
      client-id: ${OAUTH_CLIENT:client-id}
      client-secret: ${OAUTH_SECRET:secret-id}
flyway:
  url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/thunderpets}
  user: ${DATABASE_USERNAME:postgres}
  password: ${DATABASE_PASSWORD:postgres}
  baseline-on-migrate: true
  enabled: true
hibernate:
  jdbc:
    use_streams_for_binary: false