CREATE TABLE usuario (
  id      UUID NOT NULL,
  nome    CHARACTER VARYING(99) NOT NULL,
  email   CHARACTER VARYING(99) NOT NULL,
  senha   CHARACTER VARYING(99) NOT NULL,
  foto    BYTEA,
  ativo   BOOLEAN DEFAULT TRUE,
  CONSTRAINT usuario_pk PRIMARY KEY (id)
);