CREATE TABLE localizacao (
  id        UUID NOT NULL,
  latitude  CHARACTER VARYING(20) NOT NULL,
  longitude CHARACTER VARYING(20) NOT NULL,
  cidade    CHARACTER VARYING(40) NOT NULL,
  estado    CHARACTER VARYING(20) NOT NULL,
  CONSTRAINT localizacao_pk PRIMARY KEY (id)
);